version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nextjs-app
    ports:
      - "3000:3000" # Adjust the port as needed
    volumes:
      - .:/app
    command: ["yarn", "dev"]
